Update patch set 1
Patch Set 1:

Sorry, my mistake, I forgot to quote the actual failure...

----------------

external/webkit/WebKit/android/jni/WebViewCore.cpp: In member function 'void android::WebViewCore::setSizeScreenWidthAndScale(int, int, int, float, int, int, int, int, bool)':

external/webkit/WebKit/android/jni/WebViewCore.cpp:1203: error: no matching function for call to 'android::CacheBuilder::validNode(WebCore::Frame*&, WebCore::Frame*&, WTF::RefPtr<WebCore::Node>&)'

external/webkit/WebKit/android/nav/CacheBuilder.h:100: note: candidates are: static bool android::CacheBuilder::validNode(WebCore::Frame*, void*, void*)

----------------

Patch-set: 1